-- Migration: Add regional pricing tables and SKU/seller columns
-- Execute this manually in the Supabase SQL Editor

-- 1. New table: regional_prices
CREATE TABLE regional_prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_ean TEXT NOT NULL REFERENCES products(ean),
  supermarket_id BIGINT NOT NULL REFERENCES supermarkets(id),
  postal_code TEXT NOT NULL,
  region_label TEXT,
  sku_id TEXT,
  seller_id TEXT,
  seller_name TEXT,
  price NUMERIC,
  list_price NUMERIC,
  is_available BOOLEAN DEFAULT true,
  last_checked_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(product_ean, supermarket_id, postal_code)
);

-- 2. New table: regional_price_history
CREATE TABLE regional_price_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  regional_price_id BIGINT NOT NULL REFERENCES regional_prices(id),
  price NUMERIC NOT NULL,
  list_price NUMERIC,
  scraped_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Add columns to supermarket_products (nullable, no constraint changes)
ALTER TABLE supermarket_products ADD COLUMN IF NOT EXISTS sku_id TEXT;
ALTER TABLE supermarket_products ADD COLUMN IF NOT EXISTS seller_id TEXT;
ALTER TABLE supermarket_products ADD COLUMN IF NOT EXISTS seller_name TEXT;

-- 4. Indexes for query performance
CREATE INDEX idx_regional_prices_ean ON regional_prices(product_ean);
CREATE INDEX idx_regional_prices_postal ON regional_prices(postal_code);
CREATE INDEX idx_regional_prices_supermarket ON regional_prices(supermarket_id);
CREATE INDEX idx_regional_prices_last_checked ON regional_prices(last_checked_at);
CREATE INDEX idx_regional_price_history_regional_id ON regional_price_history(regional_price_id);
CREATE INDEX idx_regional_price_history_scraped ON regional_price_history(scraped_at);

-- 5. Enable RLS (matching existing table policies)
ALTER TABLE regional_prices ENABLE ROW LEVEL SECURITY;
ALTER TABLE regional_price_history ENABLE ROW LEVEL SECURITY;

-- Allow read access via anon key (same as other tables)
CREATE POLICY "Allow public read" ON regional_prices FOR SELECT USING (true);
CREATE POLICY "Allow public read" ON regional_price_history FOR SELECT USING (true);
